name: JeanMichel FRANCOIS aka toutpt
markdown: kramdown
# pygments: true
highlighter: pygments
baseurl: ""
url: http://toutpt.github.io
github_username: toutpt
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-gist
  - jekyll-paginate

paginate: 5
paginate_path: "/post/page:num/"